sonar.projectKey=ZeMechanics
sonar.projectName=ZeMechanics
sonar.sourceEncoding=UTF-8

sonar.sources=app
sonar.tests=tests

sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.junit.reportPaths=reports/test-results.xml