apiVersion: v1
kind: Service
metadata:
  name: mecanica-svc
  namespace: zemechanics
spec:
  type: NodePort
  selector:
    app: mecanica-dp
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080
