apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: zemechanics
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: mysql-pv
  resources:
    requests:
      storage: 2Gi
